/**
 * exportSecurityPDF — generate a printable security scan report from
 * the in-memory findings list (Task 2.7).
 *
 * Strategy: render the report into a hidden iframe with a print-only
 * stylesheet, then call `window.print()` on it. This keeps the
 * implementation dependency-free (no jsPDF / pdf-lib in the bundle)
 * while still producing a polished, paginated PDF when the user picks
 * "Save as PDF" in the OS print dialog.
 *
 * The same renderer can later be wrapped server-side with
 * Puppeteer/Playwright if we want fully-automated PDF generation, but
 * the in-browser flow is enough for the demo "Export PDF" button.
 */
import { type ProbeResult } from '@/components/security/ProbeTransparencyCard';

const sevColor: Record<string, string> = {
  CRITICAL: '#b91c1c',
  HIGH:     '#dc2626',
  MEDIUM:   '#d97706',
  LOW:      '#0284c7',
  INFO:     '#475569',
};

const escapeHtml = (s: unknown): string => {
  if (s === null || s === undefined) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
};

const renderReportHtml = (
  meta: { targetUrl: string; runId?: string; finishedAt?: string },
  findings: ProbeResult[],
): string => {
  const failed = findings.filter((f) => !f.passed);
  const passed = findings.filter((f) => f.passed);
  const bySev = failed.reduce<Record<string, number>>((acc, f) => {
    acc[f.severity] = (acc[f.severity] ?? 0) + 1;
    return acc;
  }, {});

  const rows = findings
    .map(
      (f, i) => `
    <tr class="${f.passed ? 'pass' : 'fail'}">
      <td>${i + 1}</td>
      <td>${escapeHtml(f.name ?? f.checkId)}</td>
      <td>
        <span class="sev" style="background:${sevColor[f.severity] ?? '#64748b'}1f;color:${sevColor[f.severity] ?? '#64748b'}">
          ${escapeHtml(f.severity)}
        </span>
      </td>
      <td>${f.passed ? 'PASS' : 'FAIL'}</td>
      <td>${escapeHtml(f.detail ?? '—')}</td>
      <td>${(f.endpointsTested ?? []).map(escapeHtml).join('<br/>')}</td>
    </tr>`,
    )
    .join('\n');

  return `<!doctype html>
<html><head><meta charset="utf-8"><title>Security scan report</title>
<style>
  *  { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         color: #0f172a; margin: 24px; }
  h1   { margin: 0 0 4px; font-size: 22px; }
  .sub { color: #475569; font-size: 12px; margin-bottom: 18px; }
  .summary { display: flex; gap: 18px; margin-bottom: 18px; flex-wrap: wrap; }
  .card { border: 1px solid #cbd5e1; border-radius: 8px; padding: 10px 14px; min-width: 110px; }
  .card .k { font-size: 11px; text-transform: uppercase; color: #64748b; }
  .card .v { font-size: 22px; font-weight: 700; }
  table { border-collapse: collapse; width: 100%; font-size: 11px; }
  th, td { border-bottom: 1px solid #e2e8f0; padding: 6px 8px; vertical-align: top; text-align: left; }
  th { background: #f1f5f9; text-transform: uppercase; font-size: 9px; color: #475569; }
  tr.fail td { background: #fef2f2; }
  .sev { padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: 700; text-transform: uppercase; }
  .footer { margin-top: 20px; color: #94a3b8; font-size: 10px; }
  @page  { size: A4; margin: 18mm; }
  @media print { body { margin: 0; } }
</style></head>
<body>
  <h1>ForgeFuzz Security Scan Report</h1>
  <div class="sub">
    Target <strong>${escapeHtml(meta.targetUrl)}</strong>
    ${meta.runId ? `· run <code>${escapeHtml(meta.runId)}</code>` : ''}
    ${meta.finishedAt ? `· finished ${escapeHtml(meta.finishedAt)}` : ''}
  </div>

  <div class="summary">
    <div class="card"><div class="k">Total probes</div><div class="v">${findings.length}</div></div>
    <div class="card"><div class="k">Passed</div><div class="v" style="color:#16a34a">${passed.length}</div></div>
    <div class="card"><div class="k">Failed</div><div class="v" style="color:#dc2626">${failed.length}</div></div>
    ${(['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as const)
      .map((s) =>
        bySev[s]
          ? `<div class="card"><div class="k">${s}</div><div class="v" style="color:${sevColor[s]}">${bySev[s]}</div></div>`
          : '',
      )
      .join('')}
  </div>

  <table>
    <thead>
      <tr><th>#</th><th>Check</th><th>Severity</th><th>Status</th><th>Detail</th><th>Endpoints tested</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">
    Generated by ForgeFuzz · ${new Date().toLocaleString()} · Use your browser's
    "Print → Save as PDF" to retain this report.
  </div>

  <script>window.addEventListener('load', () => setTimeout(() => window.print(), 250));</script>
</body></html>`;
};

export interface SecurityPDFOptions {
  targetUrl: string;
  runId?: string;
  finishedAt?: string;
  findings: ProbeResult[];
}

/** Open a print-friendly window with the report and trigger the print dialog. */
export function exportSecurityPDF(opts: SecurityPDFOptions): boolean {
  const html = renderReportHtml(
    { targetUrl: opts.targetUrl, runId: opts.runId, finishedAt: opts.finishedAt },
    opts.findings,
  );
  try {
    const win = window.open('', '_blank', 'noopener,noreferrer,width=900,height=720');
    if (!win) return false;
    win.document.open();
    win.document.write(html);
    win.document.close();
    return true;
  } catch (e) {
    console.error('Security PDF export failed', e);
    return false;
  }
}
