import React from 'react';
import IDEWorkspaceLayout from '../components/IDEWorkspaceLayout';
/**
 * Testing Tool page – separate route /workspace.
 * All request/project state and handlers are passed from App.
 */
export default function TestingToolPage({
  history,
  requests,
  collections,
  projects,
  activeRequestIndex,
  onTabSelect,
  onNewTab,
  onCloseTab,
  onTabRename,
  method,
  url,
  queryParams,
  headers,
  body,
  authType,
  authData,
  preRequestScript,
  tests,
  response,
  isLoading,
  error,
  environments,
  selectedEnvironment,
  onSelectEndpoint,
  onMethodChange,
  onUrlChange,
  onQueryParamsChange,
  onHeadersChange,
  onBodyChange,
  onAuthTypeChange,
  onAuthDataChange,
  onPreRequestScriptChange,
  onTestsChange,
  onExecute,
  onNewRequest,
  onEnvironmentChange,
  onSaveRequest,
  onAddProject,
  onCollectionsChange,
  onDeleteHistoryItem,
  environmentVariables,
  onEnvironmentVariablesChange,
  onSaveEnvironmentVariables,
  substituteVariables,
  collectionRunResults,
  onRunCollection,
  testFiles,
  onTestFilesChange,
  mockApis,
  dummyMockRequests,
  onCreateMock,
  onDeleteMock,
  onRenameMock,
  onSelectMockRequest,
  isSavedRequest,
  onUpdateRequest,
  pristineRequests,
  onCreateEnvironment,
  onActivateEnvironment,
  onRenameEnvironment,
  onDeleteEnvironment,
  environmentVariablesDirty,
  globalEnvironment,
  globalVariablesDirty,
  onGlobalVariablesChange,
  onSaveGlobalVariables,
  mockServers,
  isLoadingMocks,
  onCreateMockServer,
  onRenameMockServer,
  onDeleteMockServer,
  onToggleVisibility,
  onExecuteMockRequest,
  onSelectMockEndpoint,
  onUpdateMockServer,
  onOpenWorkspaceDetails,
  currentUserId,
    onWorkspaceUpdate,
  onWorkspaceDelete,
   onMockServerRun,
   onFetchHistoryEntry,
   activeWorkspaceId,
         onOpenCollectionRun,
      onRunCollectionWithOrder,
      onViewRunResults,
        activeEnvVars,
  inactiveEnvVars,
  activeEnvValues,
  inactiveEnvInfo,
  onShowChatbot,
}) {
  return (
    <IDEWorkspaceLayout
      history={history}
      requests={requests}
      collections={collections}
      projects={projects}
      activeRequestIndex={activeRequestIndex}
      onTabSelect={onTabSelect}
      onNewTab={onNewTab}
      onCloseTab={onCloseTab}
      onTabRename={onTabRename}
      method={method}
      url={url}
      queryParams={queryParams}
      headers={headers}
      body={body}
      authType={authType}
      authData={authData}
      preRequestScript={preRequestScript}
      tests={tests}
      response={response}
      isLoading={isLoading}
      error={error}
      environments={environments}
      selectedEnvironment={selectedEnvironment}
      onSelectEndpoint={onSelectEndpoint}
      onMethodChange={onMethodChange}
      onUrlChange={onUrlChange}
      onQueryParamsChange={onQueryParamsChange}
      onHeadersChange={onHeadersChange}
      onBodyChange={onBodyChange}
      onAuthTypeChange={onAuthTypeChange}
      onAuthDataChange={onAuthDataChange}
      onPreRequestScriptChange={onPreRequestScriptChange}
      onTestsChange={onTestsChange}
      onExecute={onExecute}
      onNewRequest={onNewRequest}
      onEnvironmentChange={onEnvironmentChange}
      onSaveRequest={onSaveRequest}
      onAddProject={onAddProject}
      onCollectionsChange={onCollectionsChange}
      onDeleteHistoryItem={onDeleteHistoryItem}
      environmentVariables={environmentVariables}
      onEnvironmentVariablesChange={onEnvironmentVariablesChange}
      onSaveEnvironmentVariables={onSaveEnvironmentVariables}
      substituteVariables={substituteVariables}
      collectionRunResults={collectionRunResults}
      onRunCollection={onRunCollection}
      testFiles={testFiles}
      onTestFilesChange={onTestFilesChange}
      mockApis={mockApis}
      dummyMockRequests={dummyMockRequests}
      onCreateMock={onCreateMock}
      onDeleteMock={onDeleteMock}
      onRenameMock={onRenameMock}
      onSelectMockRequest={onSelectMockRequest}
      isSavedRequest={isSavedRequest}
      onUpdateRequest={onUpdateRequest}
      pristineRequests={pristineRequests}
      onCreateEnvironment={onCreateEnvironment}
      onActivateEnvironment={onActivateEnvironment}
      onRenameEnvironment={onRenameEnvironment}
      onDeleteEnvironment={onDeleteEnvironment}
      environmentVariablesDirty={environmentVariablesDirty}
      globalEnvironment={globalEnvironment}
      globalVariablesDirty={globalVariablesDirty}
      onGlobalVariablesChange={onGlobalVariablesChange}
      onSaveGlobalVariables={onSaveGlobalVariables}
      mockServers={mockServers}
  isLoadingMocks={isLoadingMocks}
  onCreateMockServer={onCreateMockServer}
  onRenameMockServer={onRenameMockServer}
  onDeleteMockServer={onDeleteMockServer}
  onToggleVisibility={onToggleVisibility}
  onExecuteMockRequest={onExecuteMockRequest}
  onSelectMockEndpoint={onSelectMockEndpoint}
  onUpdateMockServer={onUpdateMockServer}
  onOpenWorkspaceDetails={onOpenWorkspaceDetails}
  currentUserId={currentUserId}
      onWorkspaceUpdate={onWorkspaceUpdate}
  onWorkspaceDelete={onWorkspaceDelete}
   onMockServerRun={onMockServerRun}
   onFetchHistoryEntry={onFetchHistoryEntry}
    activeWorkspaceId={activeWorkspaceId} 
          onOpenCollectionRun={onOpenCollectionRun}
      onRunCollectionWithOrder={onRunCollectionWithOrder}
      onViewRunResults={onViewRunResults} 
      activeEnvVars={activeEnvVars}
      inactiveEnvVars={inactiveEnvVars}
      activeEnvValues={activeEnvValues}
      inactiveEnvInfo={inactiveEnvInfo}
      onShowChatbot={onShowChatbot}  
    />
  );
}
