import React from 'react';
import IDEWorkspaceLayout from '../components/IDEWorkspaceLayout';

/**
 * Testing Tool page – separate route /workspace.
 * All request/workspace state and handlers are passed from App.
 */
export default function TestingToolPage({
  history,
  requests,
  collections,
  projects,
  activeRequestIndex,
  onTabSelect,
  onNewTab,
  onCloseTab,
  onTabRename,
  method,
  url,
  queryParams,
  headers,
  body,
  authType,
  authData,
  preRequestScript,
  tests,
  response,
  isLoading,
  error,
  environments,
  selectedEnvironment,
  onSelectEndpoint,
  onMethodChange,
  onUrlChange,
  onQueryParamsChange,
  onHeadersChange,
  onBodyChange,
  onAuthTypeChange,
  onAuthDataChange,
  onPreRequestScriptChange,
  onTestsChange,
  onExecute,
  onNewRequest,
  onEnvironmentChange,
  onSaveRequest,
  onAddProject,
  onCollectionsChange,
  onDeleteHistoryItem,
  environmentVariables,
  globalVariables,
  onEnvironmentVariablesChange,
  onGlobalVariablesChange,
  onSaveEnvironmentVariables,
  onSaveGlobalVariables,
  substituteVariables,
  collectionRunResults,
  onRunCollection,
  testFiles,
  onTestFilesChange,
  mockApis,
  dummyMockRequests,
  onCreateMock,
  onDeleteMock,
  onSelectMockRequest,
}) {
  return (
    <IDEWorkspaceLayout
      history={history}
      requests={requests}
      collections={collections}
      projects={projects}
      activeRequestIndex={activeRequestIndex}
      onTabSelect={onTabSelect}
      onNewTab={onNewTab}
      onCloseTab={onCloseTab}
      onTabRename={onTabRename}
      method={method}
      url={url}
      queryParams={queryParams}
      headers={headers}
      body={body}
      authType={authType}
      authData={authData}
      preRequestScript={preRequestScript}
      tests={tests}
      response={response}
      isLoading={isLoading}
      error={error}
      environments={environments}
      selectedEnvironment={selectedEnvironment}
      onSelectEndpoint={onSelectEndpoint}
      onMethodChange={onMethodChange}
      onUrlChange={onUrlChange}
      onQueryParamsChange={onQueryParamsChange}
      onHeadersChange={onHeadersChange}
      onBodyChange={onBodyChange}
      onAuthTypeChange={onAuthTypeChange}
      onAuthDataChange={onAuthDataChange}
      onPreRequestScriptChange={onPreRequestScriptChange}
      onTestsChange={onTestsChange}
      onExecute={onExecute}
      onNewRequest={onNewRequest}
      onEnvironmentChange={onEnvironmentChange}
      onSaveRequest={onSaveRequest}
      onAddProject={onAddProject}
      onCollectionsChange={onCollectionsChange}
      onDeleteHistoryItem={onDeleteHistoryItem}
      environmentVariables={environmentVariables}
      globalVariables={globalVariables}
      onEnvironmentVariablesChange={onEnvironmentVariablesChange}
      onGlobalVariablesChange={onGlobalVariablesChange}
      onSaveEnvironmentVariables={onSaveEnvironmentVariables}
      onSaveGlobalVariables={onSaveGlobalVariables}
      substituteVariables={substituteVariables}
      collectionRunResults={collectionRunResults}
      onRunCollection={onRunCollection}
      testFiles={testFiles}
      onTestFilesChange={onTestFilesChange}
      mockApis={mockApis}
      dummyMockRequests={dummyMockRequests}
      onCreateMock={onCreateMock}
      onDeleteMock={onDeleteMock}
      onSelectMockRequest={onSelectMockRequest}
    />
  );
}
